spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gara_photo
    username: gara
    password: ${GARA_PHOTO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  flyway:
    enabled: true
  application:
    name: gara-photo-spring-boot
  lifecycle:
    timeout-per-shutdown-phase: 15s
  server:
    shutdown: graceful
