spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
  application:
    name: gara-photo-spring-boot
  lifecycle:
    timeout-per-shutdown-phase: 15s

server:
  shutdown: graceful

application:
  repository: jdbc-client
