services:
  app-server:
    build:
      context: ./gara-photo-app-server
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - gara-photo-nw
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./photo:/opt/photo
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gara_photo
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: password
      APPLICATION_REPOSITORY: jdbc-client
      TWITTER_OAUTH1_ACCESS_TOKEN: ${GARA_PHOTO_OAUTH1_ACCESS_TOKEN:-oauth1-access-token-dummy}
      TWITTER_OAUTH1_ACCESS_TOKEN_SECRET: ${GARA_PHOTO_OAUTH1_ACCESS_TOKEN_SECRET:-oauth1-access-token-secret-dummy}
      TWITTER_API_KEY: ${GARA_PHOTO_API_KEY:-api-key-dummy}
      TWITTER_API_KEY_SECRET: ${GARA_PHOTO_API_KEY_SECRET:-api-key-secret-dummy}
      TWITTER_CLIENT_ID: ${GARA_PHOTO_CLIENT_ID:-client-id-dummy}
      TWITTER_CLIENT_SECRET: ${GARA_PHOTO_CLIENT_SECRET:-client-secret-dummy}
      TWITTER_REDIRECT_URI: ${GARA_PHOTO_REDIRECT_URI:-http://localhost/dummy}
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  mysql:
    image: mysql:8.0.40-oraclelinux9
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gara_photo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - gara-photo-nw
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  wiremock:
    image: wiremock/wiremock:3.13.0-alpine
    restart: always
    ports:
      - "28080:8080"
    volumes:
      - ./local-env/wiremock/__files:/home/wiremock/__files
      - ./local-env/wiremock/mappings:/home/wiremock/mappings
    profiles: [ "local" ]

  sonarqube:
    image: sonarqube:10.7.0-community
    ports:
    - "9000:9000"
    profiles: [ "local" ]

networks:
  gara-photo-nw:
    driver: bridge
