services:
  mysql:
    image: mysql:8.0.40-oraclelinux9
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gara_photo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
