name: CI CD Pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.gitignore'
      - 'gradle/**'
      - 'gradlew'
      - 'gradle.bat'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.gitignore'
      - 'gradle/**'
      - 'gradlew'
      - 'gradle.bat'
      - 'LICENSE.md'
      - 'README.md'
  workflow_dispatch:
    inputs:
      isDeploy:
        type: choice
        required: true
        options:
          - true
          - false

permissions:
  packages: write

env:
  TZ: 'Asia/Tokyo'

jobs:
  filter:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      isDeploy: ${{ steps.filter.outputs.isDeploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Filter
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            isDeploy:
              - 'build.gradle.kts'
              - 'gara-photo-app-server/**'

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Run detekt
        run: ./gradlew clean detekt

  konsist_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Run konsist test
        working-directory: konsist-test
        run: ../gradlew clean test

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Run unit test
        working-directory: gara-photo-app-server
        run: ../gradlew clean test

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Build
        working-directory: gara-photo-app-server
        run: gradle clean build -x test -x detekt

      - name: Run integration test
        working-directory: integration-test
        run: ../gradlew clean integrationTest

  build_and_upload_jar_file:
    if: ${{ (github.event_name == 'push' && needs.filter.outputs.isDeploy == 'true') || inputs.isDeploy == 'true' }}
    needs:
      - filter
      - detekt
      - konsist_test
      - unit_test
      - integration_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Build jar file
        working-directory: gara-photo-app-server
        run: ../gradlew clean build -x test

      - name: Upload Dockerfile and jar file
        uses: actions/upload-artifact@v4.4.0
        with:
          name: jar-and-Dockerfile
          path: |
            gara-photo-app-server/Dockerfile
            gara-photo-app-server/build/libs/gara-photo-app-server-0.0.1-SNAPSHOT.jar

  build_and_push_docker_image:
    needs: build_and_upload_jar_file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Download Dockerfile and jar file
        uses: actions/download-artifact@v4.1.8
        with:
          name: jar-and-Dockerfile

      - name: Login to GitHub container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create git tag
        run: |
          echo "TAG_NAME=1.$(date +%Y%m%d.%H%M%S)" >> $GITHUB_ENV
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Build docker image
        run: |
          docker build \
          --tag ghcr.io/$GITHUB_ACTOR/gara-photo-spring-boot:latest \
          --tag ghcr.io/$GITHUB_ACTOR/gara-photo-spring-boot:${{ env.TAG_NAME }} .

      - name: Push docker image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/gara-photo-spring-boot:latest
          docker push ghcr.io/$GITHUB_ACTOR/gara-photo-spring-boot:${{ env.TAG_NAME }}
