name: CI Pipeline

on:
  push:
    branches:
      - '**'

env:
  TZ: 'Asia/Tokyo'

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Run detekt
        working-directory: gara-photo-app-server
        run: gradle clean detektMain

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Unit test
        working-directory: gara-photo-app-server
        run: gradle clean test

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Build
        working-directory: gara-photo-app-server
        run: gradle clean build -x test -x detekt

      - name: Integration test
        working-directory: integration-test
        run: gradle clean integrationTest
