name: CI Pipeline

on:
  push:
    branches:
      - '**'

env:
  TZ: 'Asia/Tokyo'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Unit test
        working-directory: gara-photo-app-server
        run: gradle clean test

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        working-directory: gara-photo-app-server
        run: gradle clean build -x test

      - name: Integration test
        working-directory: integration-test
        run: gradle clean integrationTest
